package Models;
// Generated 2 nov. 2019 20:17:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name="departement"
    ,catalog="ginf3_jee"
)
public class Departement  implements java.io.Serializable {


     private String idDep;
     private String nom;
     private int nombreEmp;
     private Set<Employe> employes = new HashSet<Employe>(0);

    public Departement() {
    }

    public Departement(String idDep, String nom) {
        this.idDep = idDep;
        this.nom = nom;
    }
    
    public Departement(String idDep, String nom, int nombreEmp) {
        this.idDep = idDep;
        this.nom = nom;
        this.nombreEmp = nombreEmp;
    }
    public Departement(String idDep, String nom, int nombreEmp, Set<Employe> employes) {
       this.idDep = idDep;
       this.nom = nom;
       this.nombreEmp = nombreEmp;
       this.employes = employes;
    }
   
     @Id 

    
    @Column(name="ID_DEP", unique=true, nullable=false)
    public String getIdDep() {
        return this.idDep;
    }
    
    public void setIdDep(String idDep) {
        this.idDep = idDep;
    }

    
    @Column(name="NOM", nullable=false)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="NombreEmp", nullable=false)
    public int getNombreEmp() {
        return this.nombreEmp;
    }
    
    public void setNombreEmp(int nombreEmp) {
        this.nombreEmp = nombreEmp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departement")
    public Set<Employe> getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Set<Employe> employes) {
        this.employes = employes;
    }




}


