package Models;
// Generated 2 nov. 2019 20:17:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Employe generated by hbm2java
 */
@Entity
@Table(name="employe"
    ,catalog="ginf3_jee"
)
public class Employe  implements java.io.Serializable {


     private String cne;
     private Departement departement;
     private String nom;
     private String prenom;
     private int salaire;

    public Employe() {
    }

	
    public Employe(String cne, String nom, String prenom, int salaire) {
        this.cne = cne;
        this.nom = nom;
        this.prenom = prenom;
        this.salaire = salaire;
    }
    public Employe(String cne, Departement departement, String nom, String prenom, int salaire) {
       this.cne = cne;
       this.departement = departement;
       this.nom = nom;
       this.prenom = prenom;
       this.salaire = salaire;
    }
   
     @Id 

    
    @Column(name="CNE", unique=true, nullable=false)
    public String getCne() {
        return this.cne;
    }
    
    public void setCne(String cne) {
        this.cne = cne;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REF_DEP")
    public Departement getDepartement() {
        return this.departement;
    }
    
    public void setDepartement(Departement departement) {
        this.departement = departement;
    }

    
    @Column(name="NOM", nullable=false)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="PRENOM", nullable=false)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="SALAIRE", nullable=false)
    public int getSalaire() {
        return this.salaire;
    }
    
    public void setSalaire(int salaire) {
        this.salaire = salaire;
    }




}


